name: CI/CD - LECOMS API (Docker → VPS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

concurrency:
  group: lecoms-api-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: voleducanh93/lecoms-api
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login (CI)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./LECOMS
          file: ./LECOMS/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Triển khai lên VPS
      - name: Deploy on VPS (password auth)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e

            # chuẩn bị thư mục và file env (chọn /var/lecoms cho nhất quán)
            sudo mkdir -p /var/lecoms
            # đảm bảo /var/lecoms/.env đã có sẵn trên VPS (không ghi đè ở đây)

            # login dockerhub trên VPS
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # lấy image mới
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # stop & remove container cũ (nếu có)
            if [ "$(docker ps -aq -f name=lecoms-api)" ]; then
              docker rm -f lecoms-api || true
            fi

            # run container mới
            docker run -d \
              --name lecoms-api \
              --restart unless-stopped \
              --env-file /var/lecoms/.env \
              -p 8080:8080 \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # dọn rác image/containers đã dừng
            docker container prune -f || true
            docker image prune -af || true
