name: CI/CD - LECOMS API (Docker → VPS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

concurrency:
  group: lecoms-api-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: voleducanh93/lecoms-api
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Tạo SHORT_SHA bằng shell (thay cho substr() trong expressions)
      - name: Set SHORT_SHA env
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login (CI)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./LECOMS
          file: ./LECOMS/Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:sha-${{ env.SHORT_SHA }}

      - name: Deploy on VPS (password auth)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e

            # đảm bảo file env tồn tại
            if [ ! -f /var/lecoms/.env ]; then
              echo "ERROR: /var/lecoms/.env not found"; exit 1;
            fi

            # cài curl nếu thiếu (cho healthcheck)
            if ! command -v curl >/dev/null 2>&1; then
              sudo apt-get update -y && sudo apt-get install -y curl
            fi

            # login dockerhub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # pull image mới nhất (latest)
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # dừng & xoá container cũ nếu có
            if [ "$(docker ps -aq -f name=lecoms-api)" ]; then
              docker rm -f lecoms-api || true
            fi

            # chạy container mới
            docker run -d \
              --name lecoms-api \
              --restart unless-stopped \
              --env-file /var/lecoms/.env \
              -p 8080:8080 \
              --health-cmd="curl -fsS http://localhost:8080/health || exit 1" \
              --health-interval=30s --health-retries=3 --health-timeout=5s \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # dọn rác an toàn
            docker container prune -f || true
            docker image prune -af || true
