name: CI/CD - LECOMS API (Docker → VPS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: voleducanh93/lecoms-api
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login (CI)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./LECOMS   
          file: ./LECOMS/Dockerfile
          push: false
          tags: |
            voleducanh93/lecoms-api:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lecoms-api:latest

      # DÙNG PASSWORD CHO SSH
      - name: Deploy on VPS (password auth)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          password: ${{ secrets.VPS_PASSWORD }}   # <— dùng mật khẩu
          script: |
            set -e
            # đảm bảo thư mục & file env tồn tại sẵn trên VPS
            mkdir -p /opt/lecoms

            # login dockerhub trên VPS
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # pull image mới
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # stop & remove container cũ (nếu có)
            if [ "$(docker ps -aq -f name=lecoms-api)" ]; then
              docker rm -f lecoms-api || true
            fi

            # run container mới (map port 8080, nạp env từ file)
            docker run -d \
              --name lecoms-api \
              --restart unless-stopped \
              --env-file /var/lecoms/.env \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/lecoms-api:latest

            # dọn rác
            docker image prune -af || true
            docker container prune -f || true